<a href="https://colab.research.google.com/github/sam-2004/ML---basic-Template/blob/main/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [4]:
dataset = pd.read_csv('Data.csv')

In [5]:
X = dataset.iloc[:,:-1].values

In [6]:
Y = dataset.iloc[:,-1].values

In [7]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [8]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values = np.nan , strategy= 'median')
impute.fit(X[:, 1:3])
X[:, 1:3] = impute.transform(X[:, 1:3])

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 61000.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [13]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import  train_test_split

In [15]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size= 0.2,random_state= 1)

In [16]:
print(y_test)

[0 1]


In [17]:
print(x_train)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [19]:
print(y_test)

[0 1]


# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [23]:
print(X_train)

[[-0.77459667 -0.57735027  1.29099445 -0.28942984 -1.04302547]
 [-0.77459667  1.73205081 -0.77459667  0.         -0.27672104]
 [ 1.29099445 -0.57735027 -0.77459667  0.57885968  0.65987326]
 [-0.77459667 -0.57735027  1.29099445 -0.28942984 -0.27672104]
 [-0.77459667 -0.57735027  1.29099445 -1.88129397 -1.38360521]
 [ 1.29099445 -0.57735027 -0.77459667  1.15771937  1.25588781]
 [-0.77459667  1.73205081 -0.77459667  1.44714921  1.59646756]
 [ 1.29099445 -0.57735027 -0.77459667 -0.72357461 -0.53215585]]


In [22]:
print(X_test)

[[-0.77459667  1.73205081 -0.77459667 -1.44714921 -0.8727356 ]
 [ 1.29099445 -0.57735027 -0.77459667 -0.43414476  0.23414857]]
